name: kita_resto
description: "Recommended restaurant for you!"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
